import { cn } from '@/lib/utils'
import './globals.css'
import {Metadata} from "next";

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

const fontHeading = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={cn(
            'antialiased',
            fontHeading.variable,
            fontBody.variable
        )}
    >{children}</body>
    </html>
  );
}
