/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BDJBopd2ZgZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function ReviewCard({name, review, image}: {name: string, review: string, image: string}) {
  return (
    <Card className={"w-[300px] p-3 grid gap-1"}>
      <div className="flex items-center gap-2">
        <Avatar className="w-6 h-6">
          <AvatarImage src={image} alt="@shadcn" />
          <AvatarFallback>CN</AvatarFallback>
        </Avatar>
        <div className="grid gap-1">
          <h3 className="md:text-xl font-semibold">{name}</h3>
          <div className="flex items-center gap-1 text-primary">
            <StarIcon className="w-2 h-2 fill-current" />
            <StarIcon className="w-2 h-2 fill-current" />
            <StarIcon className="w-2 h-2 fill-current" />
            <StarIcon className="w-2 h-2 fill-muted stroke-muted-foreground" />
            <StarIcon className="w-2 h-2 fill-muted stroke-muted-foreground" />
          </div>
        </div>
        <MessageCircleIcon className="ml-auto w-3 h-3 text-muted-foreground" />
      </div>
      <p className="text-xs md:text-sm text-muted-foreground">
        {review}
      </p>
    </Card>
  )
}

function MessageCircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
